name: Update Buffett Summary

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transformers feedparser torch

    - name: Run update script
      run: python update_summary.py

    - name: Commit changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add api/latest.js
        git commit -m "Update latest summary" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/whiteworld33/Buffett-summary-ai.git HEAD:main
