name: Update Summary

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 UTC 기준 (한국 시간 오전 9시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install transformers feedparser

      - name: Run summary update
        run: python update_summary.py

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add latest.js
          git commit -m "Update summary" || echo "No changes to commit"
          git push
